# Generated by Django 3.2.4 on 2021-06-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='generic', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(default=2.99),
        ),
    ]
